import React, { Component } from 'react'
import "./Fractals.css";
import { Link } from 'react-router-dom';

export class Fractals extends Component {
  render() {
    return (
      <div>
        <h1 className="Fractals">Fractals</h1>
        <h1 className="fractalHeading">Mandelbrot Fractal sets</h1>
        <div class="row">
              <div class="column">
              <img className="mandelbortFractalIMG" src={require("../../images/MandelbrotSet_axis.png")} alt="Mandelbrot fractal set with axises"></img>
              </div>
              <div class="column">
              <img className="mandelbortFractalIMG2" src={require("../../images/MandelBrotSet2.png")} alt="Mandelbrot fractal set"></img>
              </div>
          </div>
        <span className="fractalInfo">
          <p>A fractal is a never-ending pattern. </p> 
          <br></br>
          <p>
            Fractals are infinitely complex patterns that are self-similar
            across different scales. They are created by repeating a simple
            process over and over in an ongoing feedback loop. Driven by
            recursion, fractals are images of dynamic systems, they are the
            images of pure Chaos.
          </p>{" "}
          <br></br>{" "}
          <p>
            Fractals exist geometrically between our familiar dimensions (the
            real numbers plane). Fractals can be found in all areas of life, and
            they occur quite commonly in nature as well. In nature fractals can
            be seen in plants, trees, rivers, coastlines, mountains, clouds,
            seashells, hurricanes and so much more. These more natural fractals
            often follow sets succh as the golden spiral which are based off a
            number sequence known as the fibonacci sequence. however, abstract
            fractals - such as the Mandelbrot Set - can be generated by a
            computer calculating a simple equation over and over.{" "}
          </p>
          <br></br>
          <p>
            This is what my focuses is on, abstract fractals and most
            particularly the Mandelbrot Set. The equation for a Mandelbrot set
            generally looks like this in+1 = in2 + c. In this equation, c and i
            are complex or imaginary numbers and n is zero or any positive
            integer (i.e. natural number). What this equation basically means is
            that the next i value in the set is equal to its previous i value
            square plus some complex number, c. The equation is built upon sets
            of itself essentially.
          </p>
          <br></br>
          <p>If you would like to view some other fractal generator websites I would highly reccomend these:</p>
          <p><a href="https://sciencevsmagic.net/fractal/#0060,0090,1,1,0,0,1" target="_blank">Science vs.
        Magic</a></p>
        <p><a href="http://usefuljs.net/fractals/" target="_blank">UsefulJS online fractal generator</a></p>
          <br></br>
          <p>
            Below I have included some videos of fractals created by{" "}
            <a
              href="https://www.youtube.com/c/MathsTown"
              target="_blank"
              type="media_type"
            >
              Math Town
            </a>
          </p>
        </span>

        <iframe
          src="https://www.youtube.com/embed/pCpLWbHVNhk?start=8?&autoplay=0"
          title="YouTube video player"
          frameborder="0"
          allow="fullscreen; accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        >
          MandelBrot Fractal
        </iframe>
        <iframe
          src="https://www.youtube.com/embed/w6RPasYEZk4"
          title="YouTube video player"
          frameborder="0"
          allow="fullscreen; accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        >
          Teddy Bear
        </iframe>
        <iframe
          width="560"
          height="315"
          src="https://www.youtube.com/embed/Ujvy-DEA-UM"
          title="YouTube video player"
          frameborder="0"
          allow="fullscreen; accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        >
          11 Dimensions
        </iframe>
      </div>
    );
  }
}

export default Fractals