import React from "react";
import "./singleBlog1.css";

export default function Blog6() {
  return (
    <div id="top" className="Blog6">
      <h2 className="prepWork">
        Internet Artwork - Preparatory work, Why Fractals?
      </h2>
      <br></br>
      <p>
        Throughout my life I have always been intrigued by the unknown and the
        complex. In grade 10 I was introduced to the idea of imaginary numbers
        or i the square root of -1 (√-1). This number is theoretically
        impossible, but through a series of logical inductions one can arrive at
        a proof that √-1 does in fact exist. This blew my mind and I was
        immediately invested in the concept. After doing more research on the
        topic of i, I came across an interesting topic, fractals, which are
        produced by an equation using the number i. The idea is that a fractal
        is something that is built from infinitely smaller parts of itself. A
        fractal is a never-ending pattern. Fractals are infinitely complex
        patterns that are self-similar across different scales. They are created
        by repeating a simple process over and over in an ongoing feedback loop.
        Driven by recursion, fractals are images of dynamic systems – they are
        the images of pure Chaos.[1]
      </p>
      <br></br>
      <p>
        Fractals exist geometrically between our familiar dimensions (the real
        numbers plane). Fractals can be found in all areas of life, and they
        occur quite commonly in nature as well. In nature fractals can be seen
        in plants, trees, rivers, coastlines, mountains, clouds, seashells,
        hurricanes and so much more. These more natural fractals often follow
        sets succh as the golden spiral which are based off a number sequence
        known as the fibonacci sequence. however, abstract fractals – such as
        the Mandelbrot Set – can be generated by a computer calculating a simple
        equation over and over. This is what my focuses is on, abstract fractals
        and most particularly the Mandelbrot Set.
      </p>
      <br></br>
      <p>
        The equation for a Mandelbrot set generally looks like this{" "}
        <i>
          <b>
            i<sub>n+1</sub> = i<sub>n</sub>
            <sup>2</sup> + c
          </b>
        </i>
        . In this equation, c and i are complex or imaginary numbers and n is
        zero or any positive integer (i.e. natural number). What this equation
        basically means is that the next i value in the set is equal to its
        previous i value square plus some complex number, c. The equation is
        built upon sets of itself essentially. The equation was discovered by
        Benoît Mandelbrot in 1979 [2]. Using IBM’s computers, he was able to use
        computer graphics to create and display fractal geometric images, this
        allowed him to show how visual complexity can be created from simple
        rules.
      </p>
      <br></br>
      <p>
        I have found fractals to be one of the most beautiful and complex things I
        have ever seen. Therefore, the net art I have chosen to create is a
        website that allows one to view a Mandelbrot fractal. The purpose of the
        website is to give a good understanding of what fractals are and then to
        allow one to view a fractal in detail. I have researched various fractal
        generators online, most cost money and are quite complex to use. They
        work off of applications that run the software as an application on your
        computer. These include websites like Mandelbulb 3D, Apophysis and
        XenoDream [3][4][5]. However, I was able to find some websites that
        allowed you to generate and view fractals. The first was <a href="https://sciencevsmagic.net/fractal/#0060,0090,1,1,0,0,1" target="_blank">Science vs.
        Magic</a>[6], and is a fantastic website that teaches you how fractals are
        built from recursion and iterative feedback loops. The website uses line
        algorithms and builds upon them to create very intricate and beautiful
        equations. The <a href="http://usefuljs.net/fractals/" target="_blank">UsefulJs’ online fractal generator</a> [7] website is another
        very good website that allows one to view various fractal sets such as
        the mandelbrot set in great detail and it also allows you to alter the
        equation used to produce the set, in order to produce new sets.
      </p>
      <br></br>
      <p>
        With my website I will look for an external Javascript plugin that will
        allow me to generate a Mandelbrot fractal set that the viewer of the
        webpage can explore in great detail. I will use a fractal generator to
        produce and extremely high resolution fractal image that the user can
        zoom into in order to see how a fractal is built upon infinite parts of
        itself. I feel the best way to understand exactly what a fractal is, is
        to see it and explore its parts. I personally love to watch videos of
        fractal sets rendered by super computers. They are beautiful and the way
        they continue to create themselves endlessly is super entertaining to
        watch and quite relaxing. I feel I may occur some technical concerns
        here when it comes to implementing the fractal generator on the website
        as the code is complex and will be tricky to understand and utilize for
        my own purposes. However, I will do further research into external
        fractal plugins for javascript and react.
      </p>
      <br></br>
      <p>
        I hope that by creating this website, I will be able to explore fractals
        further and gain a deeper grasp and understanding of what they are, how
        they are created and there purposes in all areas of life. I hope to
        share the love I have for fractals through my website and hopefully
        create that love in you too.
      </p>
      <br></br>
      <h3>References:</h3>
      <br></br>
      <p>
        [1] Fractalfoundation.org. n.d. What are Fractals? – Fractal Foundation.
        [online] Available at:
        https://fractalfoundation.org/resources/what-are-fractals/#:~:text=A%20fractal%20is%20a%20never,systems%20%E2%80%93%20the%20pictures%20of%20Chaos.
        [Accessed 3 June 2022].
      </p>
      <br></br>
      <p>
        [2]Wikipedia. n.d. Mandelbrot set - Simple English Wikipedia, the free
        encyclopedia. [online] Available at:
        https://simple.wikipedia.org/wiki/Mandelbrot_set#:~:text=The%20Mandelbrot%20set%20can%20be,positive%20integer%20(natural%20number).
        [Accessed 3 June 2022].
      </p>
      <br></br>
      <p>
        [3]Mandelbulb.com. n.d. Mandelbulb.com | The 3D Fractal Experience.
        [online] Available at: https://www.mandelbulb.com/ [Accessed 3 June
        2022].
      </p>
      <br></br>
      <p>
        [4]SourceForge. n.d. Apophysis. [online] Available at:
        https://sourceforge.net/projects/apophysis/ [Accessed 3 June 2022].
      </p>
      <br></br>
      <p>
        [5]Xenodream.com. XenoDream Program - 3D graphics software. [online]
        Available at: https://xenodream.com/xenodream1.htm [Accessed 3 June
        2022].
      </p>
      <br></br>
      <p>
        [6]Disseldorp, N., n.d. FRACTAL MACHINE. [online] Sciencevsmagic.net.
        Available at: https://sciencevsmagic.net/fractal/#0060,0090,1,1,0,0,1
        [Accessed 3 June 2022].
      </p>
      <br></br>
      <p>
        [7]Williams, C., n.d. Online Fractal Generator. [online] Usefuljs.net.
        Available at: http://usefuljs.net/fractals/ [Accessed 3 June 2022].
      </p>
      <br></br>
      <h2 className="prepWork2">
        Internet Artwork Prototype - Discussion and Future Development
      </h2>
      <br></br>
      <p>
        My website, Fractally, is coming along quite nicely. I am in the
        prototyping phase of development. For this release of the prototype I
        have been working on implementing a fractal generator plugin that will
        allow the viewer to view a detailed Mandelbrot set. The plugin uses an
        open source GNU general public license javascript application that
        generates the MandelBrot fractal through an algorithm created by Raphael
        Pedicini. The code is split into two independent parts: app.js and
        fractal.js. The app handles all the setup and user interaction, and
        communicates these to the fractal using the fractal's api. The fractal
        just calculates and draws itself based on the settings it receives from
        the app. I have been working on implementing the code into my website,
        however it is extremely complex and has taken quite some time to get my
        head around. Therefore, I have decided that for this prototype I will
        not include the fractal generator and will instead include it in the
        final release of the website. I feel this is necessary as the website
        still needs work in places elsewhere and as I will need more time to get
        the fractal generator working, I feel it would be best to work on these
        areas of improvement so that the website is almost entirely complete
        without the fractal generator. This will allow me to focus my efforts on
        getting the fractal generator working for the final release and allow me
        to complete the rest of the website in the meantime.
      </p>
      <br></br>
      <p>
        For this release there are a few bugs that I need to fix. The first is
        my images which are too large and dont link correctly in certain areas.
        I would like to add an individual viewing window for each of my blogs so
        one does not have to scroll so much, and possibly add a back to the top
        button on my blog page. I will implement a footer to the website with
        copyright information and my personal information for contact purposes.
        I will fill the site will all the necessary information to make it feel
        more populated and complete. I have designed the website to have feels
        of both early html mathematics websites, through the simple text styles
        and isolated areas of text and image, and modern ‘ios’ like applications
        through the navbar design and simple but clean User Interface.
      </p>
      <br></br>
      <p>
        As of this moment the website does not particularly stand as an
        interactable artwork, although it may be very visually stimulating and
        appealing making it appear ‘artsy’, it is still not yet fully
        interactable as the main point of the website, the fractal generator,
        will not be available yet. However, I do believe as it is now the
        website provides a beautiful insight into the art of fractals and
        displays their beauty in very efficient and simple manner. For the final
        release of the website, the fractal generator will be working and then I
        believe the website can be termed a brilliant example of an internet
        artwork.
      </p>
      <br></br>
      <p>By: Matthew Cresswell</p>
      <br></br>
    </div>
  );
}
