import React from 'react'
import "./singleBlog1.css"

export default function Blog8() {
  return (
    <div className="Blog8">
      <h2>Fractal Design in African Art</h2>
            <br></br>
            <p>Africa is a continent that is rich in culture and history. Due to its large ethnic and cultural diversity many different traditions and practices have been established, and due to this many forms of creation and art. What is most unique about the art that comes from Africa in comparison to the rest of the world, is that it is mostly created due to societal needs or as a form of creativity, tradition and expression, rather than a means of wealth… It was created as art with a purpose [1]. Many different forms of art stem from Africa, these include Basket making, beadworking, painting, carving, sculpting and so much more. There has always been a large focus on the aesthetic design of African artworks and much interest has been taken in its shapes, colours, uses and meanings. However, very little focus has been put into the technical and mathematical systems, as well as the cultural and political impacts, underlying the design of such artworks.  
</p>
            <br></br>
            <p>In recent years more research has been done around African art and the mathematical constructs involving its creation, particularly fractal geometry. Ron Eglash, an author and professor who is widely known for his works in ethnomathematics, ethnocomputing and the diverse relationships between mathematics and culture, writes on the prevalence of Fractals in African Culture in his book “African Fractals: Modern Computing and Indigineous Design”[2]. Research has shown some rather interesting results, and it indicates that fractals are well entangled in the roots of african art and design. Fractal and mathematical design has been found in traditional ways of constructing homesteads, pattern generation, designing sigils and religious rites. The presence of these mathematical forms in the core design of cultural and societal artefacts suggests a far more advanced understanding of mathematics in early African society than was widely thought[3]. Attention can be drawn to the structural patterns of pre colonial African settlements which tend to follow a fractal design, this Egland says, is simply due to the fact that fractal design is widely present in African culture and its design practices.
</p>
            <br></br>
            <p>In an attempt to further understand this fractal design within African art, I visited the Wits Art Museum which is known to have an extensive collection of African art and history. My visit was enjoyable, however, not as insightful as I thought it would be. I struggled to find fractal design present in the majority of the artworks such as the paintings and sculptures, which just appeared to be abstract or of creative influence rather than mathematical in design. In the beadwork I could find occurrences of iteration and multiple occurrences of linear scaling and particularly in the use of linear-concentrically scaled triangles that were present in almost all of the beadwork items in the museum. I still wasn’t too convinced as these items followed very basic iterative sets such as 1,2,3,4,... which is a very basic set of iteratively scaled numbers and not so much true recursion.</p>
            <br></br>
            <p>The traditional handwoven baskets, however, were laced with evidence of recursion, fractals and fractal integrated design. The traditional zulu baskets are made from ilala palm fronds which are stripped and dyed using natural materials such as mud, flowers, charcoal, bark, roots and other materials found in the area [4]. These baskets were used to store food and grain, as well as to carry alcohol and other liquids. The larger baskets are often woven by brides-to-be or given as wedding gifts and require significantly more time and effort to make and can sometimes take up to an entire year to complete. More elaborately designed and intricately patterned baskets denote the relative wealth and power of the family that owns it.
</p>
            <br></br>
            <p>The Fibonacci spiral or more accurately Archimedean spiral of the baskets weaved spines was present in all the designs of the baskets at the museum. One basket followed a beautiful iterative pattern of increasingly larger diamonds, each a different colour. The diamonds on the basket are said to represent femininity and a string of diamonds represents the shield of Shaka.When viewed vertically the spine that the basket follows when being made follows the shape of an archimedean spiral. Due to the presence of this spiral at the base of its construction it can be seen that the baskets follow a scaling design and are designed to follow an eulerian path when being created (Centre-outwards, or top-to-bottom). The presence of recursion in both the design and aesthetics of the basket are excellent examples of the prevalence of fractal design in African culture. A bowl that was placed at the end of the exhibition, made for the 1995 rugby world cup, was created in a beautiful archimedean spiral shape and was made up of linearly-scaled rings or linearly-concentric circles of different colours. 
</p>
            <br></br>
            <p>I found these examples to be good accounts of fractal geometry present within African culture, however, I wasn't fully satisfied with this evidence. Upon doing more research I found a picture of a flat bowl stored at the Wits Art Museum created by Esta Zulu, a Tintsaba (Master Weavers) from eSwatini. The artwork's name is “Spiralling Energy” and it was created in 2014. The bowl is woven from agave sisalana (sisal) and lutindzi grass, both common plants found in Southern Africa. The bowl has a beautiful black archimedean spiral across its surface. No other patterns or geometrics are present on the bowl besides the spiral. The bowl is a beautiful construct composed entirely of archimedean spirals [5]. The actual material of the bowel is laced together in an archimedean spiral, with the bowl being created from the inner point and expanding outwards. The spiral on the bowl is entirely fractal in nature as its shape is that of a point moving on a line that is rotated uniformly about the origin (an Archemedian spiral) and the spiral is composed of a sequence of lines that iteratively increase in width as it expands outwards from the centre of the bowl. I believe that this bowl is a perfect example of fractal design in African culture and is so relevant to the subject that one could even consider it a caricature of fractal design in African art. I believe the artist wanted to place focus on the nature of the spiral itself by incorporating a spiral into every element of its design, she is commenting on that nature of the spiral in our everyday lives. It is a commonly known fact that the fibonacci sequence can be found in almost all of nature, and I feel that this bowl highlights that.
</p>
            <br></br>
            <p>These bowls and baskets were not designed to represent the nature of fractals in a physical manner, in fact these bowls follow fractal design because this is what made the design of these pieces possible. They are just rules and processes that these cultures follow and have found to work and therefore they have integrated them into their society. The evidence of iterative design in Africa is widely prevalent from the designs in straw walls, to settlement construction. The Chokwe people of Angola have a tradition of drawing eulerian paths in the sand. This was done as an age based initiation system, which one would have to learn at a certain age. This allowed for iterations of knowledge to be passed from one generation to another and to allow for more knowledge to be shared and gained as one grew older.</p>
            <br></br>
            <p>The evidence I have provided above is sufficient enough to say that fractals are deeply woven in the history and culture of Africa, and that African fractals are not just the result of spontaneous intuition but are, however, ingrained in African tradition as rule-bound techniques that can be seen as equivalent to Western mathematics. The significance of the presence of fractals in African history is that it can help to break down long held myths and misconceptions of Africans being inactive agents in history that have contributed little to the global fields of science, technology and mathematics. This enate mathematical design shows that the African peoples were significantly more advanced than is widely believed, and had a far better understanding of mathematics, patterns, and self-organisation. By examining and understanding these design decisions and traditions of iterative and mathematically influenced design, we can break down racist mindsets by helping to decompose connotations that African cultures were not technologically advanced and had little understanding of mathematics, and can help to find many strategies to promote technological research, self organisation, and egalitarianism.
</p>
            <br></br>
            <h3>References:</h3>
            <br></br>
            <p>[1]Collections.dma.org. 2022. Cultures and Traditions - African Art in Context - DMA Collection Online. [online] Available at: https://collections.dma.org/essay/oV18eGaO [Accessed 3 April 2022].
</p>
            <br></br>
            <p>[2] Eglash, R., 1999. African fractals: Modern computing and Indigineous design. New Brunswick: Rutgers university press.
</p>
            <br></br>
            <p>[3] Bristow, T. (2016). Access to Ghosts. In L. O. T. Hiendrich, Sean (Ed.), African Futures. Germany: Kerber Verlag.
</p>
            <br></br>
            <p>[4] Baskets of Africa. 2022. Weaving Zulu Ilala Palm Baskets in South Africa - Baskets of Africa. [online] Available at: https://basketsofafrica.com/wp/weaving-zulu-ilala-palm-baskets-in-south-africa/ [Accessed 3 April 2022].</p>
            <br></br>
            <p>[5] Esta Zulu, Tintsaba (Master Weavers), eSwatini, “Spiralling Energy”, 2014, woven agave sisalana (sisal) and lutindzi grass, 25 x 125,5 x 125,5 cm. Standard Bank African Art Collection (Wits Art Museum). https://www.facebook.com/WitsArtMuseum/photos/a.158849150796906/5193800203968417/[Acessed 3 April 2022]</p>
            <br></br>
            
    </div>
  )
}