import React from "react";
import '../App.css';
import { Button } from './Button';
import './fractalPage.css';


function FractalPage() {
    return (
      <div id='fractalContainer' className="fractal-container">
        <div className="Fractal_info">
          <h4>Fractals</h4>
          <span>A fractal is a never-ending pattern.</span>
          <br></br>
          <span>
            Fractals are infinitely complex patterns that are self-similar
            across different scales. They are created by repeating a simple
            process over and over in an ongoing feedback loop (i.e. an Iterative loop). Driven by
            recursion, fractals are images of dynamic systems... They are the pictures of
            Chaos. Geometrically, they exist in between our familiar dimensions.
            Fractal patterns are extremely familiar, since nature is full of
            fractals. For instance: trees, rivers, coastlines, mountains,
            clouds, seashells, hurricanes, etc. Abstract fractals - such as the
            Mandelbrot Set - can be generated by a computer calculating a simple
            equation over and over.  - Fractal Foundation
            <br></br>
          </span>         
        <br></br>
        <span>this website will host a madelbrot fractal simulator that will allow one to view and zoom into a mandelbrot fractal in order to understand and see the beauty of its infiniteness.</span>
        </div>
        <div className="fractal-btns">
          <Button
            className="btns"
            buttonStyle="btn--primary"
            buttonSize="btn--large"
          >
            START
          </Button>
        </div>
      </div>
    );
    //<iframe src="https://www.youtube.com/embed/pCpLWbHVNhk?start=8?&autoplay=1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><h1>Mandelbrot Fractal</h1>
            
}

 

export default FractalPage;